const colours = [
  "White",
  "Black",
  "Grey",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Orange",
  "Brown",
  "Red",
  "Pink",
  "Purple",
  "Silver",
];

const adjectives = [
  "Adorable",
  "Adventurous",
  "Aggressive",
  "Amused",
  "Angry",
  "Annoyed",
  "Anxious",
  "Arrogant",
  "Attractive",
  "Beautiful",
  "Bewildered",
  "Bored",
  "Brave",
  "Busy",
  "Calm",
  "Careful",
  "Cautious",
  "Cheerful",
  "Clever",
  "Clumsy",
  "Confused",
  "Courageous",
  "Crazy",
  "Curious",
  "Dangerous",
  "Defiant",
  "Delightful",
  "Depressed",
  "Determined",
  "Dizzy",
  "Doubtful",
  "Dull",
  "Eager",
  "Elated",
  "Elegant",
  "Embarassed",
  "Energetic",
  "Enthusiastic",
  "Evil",
  "Famous",
  "Fancy",
  "Fierce",
  "Filthy",
  "Foolish",
  "Frantic",
  "Friendly",
  "Gentle",
  "Glamorous",
  "Grumpy",
  "Handsome",
  "Hilarious",
  "Homeless",
  "Hungry",
  "Innocent",
  "Jittery",
  "Jolly",
  "Kind",
  "Lazy",
  "Lively",
  "Lonely",
  "Mysterious",
  "Naughty",
  "Nervous",
  "Perfect",
  "Poor",
  "Powerful",
  "Proud",
  "Puzzled",
  "Selfish",
  "Shy",
  "Sleepy",
  "Sparkling",
  "Tired",
  "Troubled",
  "Ugly",
  "Unusual",
  "Wicked",
  "Worried",
  "Zealous",
  "Exuberant",
  "Wistful",
  "Imaginary",
  "Sceptical",
  "Methodical",
  "Whimsical",
];

const animals = [
  "Lion",
  "Tiger",
  "Bear",
  "Wolf",
  "Dog",
  "Cat",
  "Dragon",
  "Fox",
  "Snake",
  "Elephant",
  "Meercat",
  "Horse",
  "Buffalo",
  "Panda",
  "Pig",
  "Cow",
  "Chicken",
  "Swan",
  "Eagle",
  "Bat",
  "Rhino",
  "Monkey",
  "Parrot",
  "Goat",
  "Shark",
  "Unicorn",
  "Frog",
  "Whale",
  "Kangaroo",
  "Rabbit",
  "Mouse",
  "Armadillo",
  "Dolphin",
];

export default function generatePassword() {
  let password = "";

  const randomAdjective = adjectives[Math.floor(Math.random() * (adjectives.length - 1))];
  console.log("adjective", randomAdjective);

  const randomColour = colours[Math.floor(Math.random() * (colours.length - 1))];
  console.log("random number", Math.floor(Math.random() * (colours.length - 1)));
  console.log("colour", randomColour);

  const randomAnimal = animals[Math.floor(Math.random() * (animals.length - 1))];
  console.log("animal", randomAnimal);

  const randomNumber = Math.floor(Math.random() * 99);
  const randomTwoDigitNumber = randomNumber > 9 ? randomNumber : "0" + randomNumber;

  password = `${randomAdjective}${randomColour}${randomAnimal}${randomTwoDigitNumber}`;

  return password;
}
